CREATE TABLE [dbo].[BOOKS]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TITLE] NVARCHAR(50) NULL, 
    [AUTHOR] NVARCHAR(50) NULL, 
    [PRICE] INT NULL, 
    [CATEGORY] NVARCHAR(50) NULL, 
    [DATE] DATE NULL, 
    [RATE] FLOAT NULL, 
    [COVER] IMAGE NULL
)
